# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Admin/Documents/Chaos_Based_Symmetric_Image_Encryption/vivado/Arty-Z7-20-Master.xdc

# Block Designs: bd/TRNG_BOCK/TRNG_BOCK.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TRNG_BOCK || ORIG_REF_NAME==TRNG_BOCK} -quiet] -quiet

# IP: bd/TRNG_BOCK/ip/TRNG_BOCK_S_TRNG_0_0/TRNG_BOCK_S_TRNG_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TRNG_BOCK_S_TRNG_0_0 || ORIG_REF_NAME==TRNG_BOCK_S_TRNG_0_0} -quiet] -quiet

# IP: bd/TRNG_BOCK/ip/TRNG_BOCK_processing_system7_0_0/TRNG_BOCK_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TRNG_BOCK_processing_system7_0_0 || ORIG_REF_NAME==TRNG_BOCK_processing_system7_0_0} -quiet] -quiet

# IP: bd/TRNG_BOCK/ip/TRNG_BOCK_ps7_0_axi_periph_0/TRNG_BOCK_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TRNG_BOCK_ps7_0_axi_periph_0 || ORIG_REF_NAME==TRNG_BOCK_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/TRNG_BOCK/ip/TRNG_BOCK_rst_ps7_0_100M_0/TRNG_BOCK_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TRNG_BOCK_rst_ps7_0_100M_0 || ORIG_REF_NAME==TRNG_BOCK_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/TRNG_BOCK/ip/TRNG_BOCK_TRNG_IP_0_1/TRNG_BOCK_TRNG_IP_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TRNG_BOCK_TRNG_IP_0_1 || ORIG_REF_NAME==TRNG_BOCK_TRNG_IP_0_1} -quiet] -quiet

# IP: bd/TRNG_BOCK/ip/TRNG_BOCK_auto_pc_0/TRNG_BOCK_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TRNG_BOCK_auto_pc_0 || ORIG_REF_NAME==TRNG_BOCK_auto_pc_0} -quiet] -quiet

# XDC: bd/TRNG_BOCK/ip/TRNG_BOCK_processing_system7_0_0/TRNG_BOCK_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TRNG_BOCK_processing_system7_0_0 || ORIG_REF_NAME==TRNG_BOCK_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/TRNG_BOCK/ip/TRNG_BOCK_rst_ps7_0_100M_0/TRNG_BOCK_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TRNG_BOCK_rst_ps7_0_100M_0 || ORIG_REF_NAME==TRNG_BOCK_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/TRNG_BOCK/ip/TRNG_BOCK_rst_ps7_0_100M_0/TRNG_BOCK_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TRNG_BOCK_rst_ps7_0_100M_0 || ORIG_REF_NAME==TRNG_BOCK_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/TRNG_BOCK/ip/TRNG_BOCK_auto_pc_0/TRNG_BOCK_auto_pc_0_ooc.xdc

# XDC: bd/TRNG_BOCK/TRNG_BOCK_ooc.xdc
